---
- name: "create alert data dir with proper perms"
  file:
    path: "{{alertmanager_data_path}}"
    owner: "{{prometheus_container_user}}"
    group: "{{prometheus_container_group}}"
    mode: "0770"
    state: "directory"

- name: "generate alertmanager configuration"
  template:
    src: "alertmanager.yml.j2"
    dest: "{{promfriends_config_path}}/alertmanager.yml"
    owner: "{{prometheus_container_user}}"
    group: "{{prometheus_container_group}}"
    mode: "0640"
  register: alertmanager_config

- include_tasks: "docker.yml"
  vars:
    context: "alertmanager"
    image: "{{alertmanager_image}}"
    publish: "{{alertmanager_publish}}"
    use_command: >-
      --config.file=/alertmanager.yml
      --web.config.file=/web_config.yml
      --web.listen-address={{prometheus_address}}:{{alertmanager_port}}
      --storage.path=/data
      --data.retention={{alertmanager_retention}}
    volume:
      - "{{promfriends_config_path}}/web_config.yml:/web_config.yml:ro"
      - "{{promfriends_config_path}}/alertmanager.yml:/alertmanager.yml:ro"
      - "{{alertmanager_data_path}}:/data:rw"
      - "{{promfriends_config_path}}/server.crt:/server.crt:ro"
      - "{{promfriends_config_path}}/server.key:/server.key:ro"
      - "{{promfriends_config_path}}/ca.crt:/ca.crt:ro"
    changed: "{{alertmanager_config.changed or promfriends_certs_changed}}"

- name: "ensure alertmanager container is running"
  uri:
    url: "https://{{inventory_hostname}}:{{alertmanager_port}}/"
    ca_path: "{{promfriends_config_path}}/ca.crt"
    client_cert: "{{promfriends_config_path}}/server.crt"
    client_key: "{{promfriends_config_path}}/server.key"
  register: alertmanager_status
  until: alertmanager_status.status == 200
  retries: 5
  delay: 10
