---
- name: "create common directories"
  file:
    path: "{{item}}"
    owner: "{{prometheus_container_user}}"
    group: "{{prometheus_container_group}}"
    mode: "0770"
    state: "directory"
  with_items: "{{promfriends_directories}}"
