---
- name: "create data dir with proper perms"
  file:
    path: "{{prometheus_data_path}}"
    owner: "{{prometheus_container_user}}"
    group: "{{prometheus_container_group}}"
    mode: "0770"
    state: "directory"

- name: "generate prometheus configuration"
  template:
    src: "prometheus.yml.j2"
    dest: "{{promfriends_config_path}}/prometheus.yml"
    owner: "{{prometheus_container_user}}"
    group: "{{prometheus_container_group}}"
    mode: "0660"
  register: prom_config

- include_tasks: "docker.yml"
  vars:
    context: "{{prometheus_docker_name}}"
    image: "prom/prometheus:{{prometheus_version}}"
    publish:
      - "{{ansible_default_ipv4.address}}:9090:9090"
    volume:
      - "{{promfriends_config_path}}:/etc/prometheus:ro"
      - "{{prometheus_data_path}}:/prometheus"
      - "{{promfriends_config_path}}/web_config.yml:/web_config.yml:ro"
      - "{{promfriends_config_path}}/server.crt:/server.crt:ro"
      - "{{promfriends_config_path}}/server.key:/server.key:ro"
      - "{{promfriends_config_path}}/ca.crt:/ca.crt:ro"
    use_command: >
      --storage.tsdb.retention={{prometheus_retention_time}}
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.config.file=/web_config.yml
      --log.level={{prometheus_log_level}}
    changed: "{{prom_config.changed}}"

- name: "ensure prometheus container is running"
  delegate_to: "localhost"
  become: false
  uri:
    url: "https://{{inventory_hostname}}:9090/"
    ca_path: "{{promfriends_docker_cacert_path}}"
    client_cert: "{{promfriends_docker_cert_path}}"
    client_key: "{{promfriends_docker_key_path}}"
  register: core_status
  until: core_status.status == 200
  retries: 5
  delay: 10
