---
- name: "check for promfriend {{context}}"
  delegate_to: "localhost"
  become: false
  command: >
    docker -H tcp://{{promfriends_docker_host}}:2376
    --tlscert {{promfriends_docker_cert_path}}
    --tlskey {{promfriends_docker_key_path}}
    --tlscacert {{promfriends_docker_cacert_path}}
    --tlsverify
    inspect --format \{\{.State.Running\}\} {{context}}
  ignore_errors: true
  changed_when: false
  register: container_check

- name: "run container {{context}}"
  become: false
  delegate_to: "localhost"
  docker_container:
    name: "{{context}}"
    docker_host: "tcp://{{promfriends_docker_host}}:2376"
    ca_cert: "{{promfriends_docker_cacert_path}}"
    client_key: "{{promfriends_docker_key_path}}"
    client_cert: "{{promfriends_docker_cert_path}}"
    tls_hostname: "{{promfriends_docker_host}}"
    comparisons:
      "*": "strict"
    recreate: true
    published_ports: "{{publish|default(omit)}}"
    restart_policy: "unless-stopped"
    pull: true
    image: "{{image}}"
    command: "{{use_command|default(omit)}}"
    volumes: "{{volume|default(omit)}}"
    capabilities: "{{caps|default(omit)}}"
    env: "{{use_env|default(omit)}}"
    dns_servers: "{{promfriends_dns_servers|default(omit)}}"
    labels: "{{labels|default(omit)}}"
    validate_certs: true
    ssl_version: "TLS"  # whut
    user: "{{user|default(prometheus_container_uid)}}"
    groups: "{{[prometheus_container_gid] + container_groups|default([])}}"
    log_driver: "{{promfriends_logdriver}}"
    log_options: "{{promfriends_logoptions}}"
  when: >
    (container_check.rc == 1 or
    container_check.stdout == "false" or
    promfriends_web_config.changed or
    changed|default(False))
