---
- name: "get container information"
  become: false
  delegate_to: "localhost"
  docker_container_info:
    name: "{{context}}"
    tls: true
    ca_cert: "{{yopo_docker_cacert_path}}"
    client_key: "{{yopo_docker_key_path}}"
    client_cert: "{{yopo_docker_cert_path}}"
    tls_hostname: "{{inventory_hostname}}"
    validate_certs: true
    ssl_version: "TLS"  # whut
    docker_host: "tcp://{{inventory_hostname}}:2376"
  register: promfriend_container_info
  no_log: "{{yopo_debug|default('') != 'true'}}"

- set_fact:
    promfriend_container_running: "{{promfriend_container_info.container\
    ['State']['Running']|default(False)|bool}}"
    promfriend_running_image: "{{promfriend_container_info.container\
    ['Config']['Image']|default('')|trim}}"

- name: "run container {{context}}"
  become: false
  delegate_to: "localhost"
  docker_container:
    name: "{{context}}"
    docker_host: "tcp://{{promfriends_docker_host}}:2376"
    ca_cert: "{{promfriends_docker_cacert_path}}"
    client_key: "{{promfriends_docker_key_path}}"
    client_cert: "{{promfriends_docker_cert_path}}"
    tls_hostname: "{{promfriends_docker_host}}"
    comparisons:
      "*": "strict"
    recreate: true
    published_ports: "{{publish|default(omit)}}"
    restart_policy: "unless-stopped"
    privileged: "{{privileged|default(False)}}"
    pull: true
    devices: "{{use_devices|default(omit)}}"
    image: "{{image}}"
    command: "{{use_command|default(omit)}}"
    volumes: "{{volume|default(omit)}}"
    capabilities: "{{caps|default(omit)}}"
    env: "{{use_env|default(omit)}}"
    dns_servers: "{{promfriends_dns_servers|default(omit)}}"
    labels: "{{labels|default(omit)}}"
    validate_certs: true
    ssl_version: "TLS"  # whut
    user: "{{user|default(prometheus_container_uid)}}"
    groups: "{{[prometheus_container_gid] + container_groups|default([])}}"
    log_driver: "{{promfriends_logdriver}}"
    log_options: "{{promfriends_logoptions}}"
  when: >
    (not promfriend_container_running)
    or promfriend_running_image != image
    or changed|default(False)
