---
- include_tasks: "base.yml"

- include_tasks: "snmp.yml"

- include_tasks: "blackbox.yml"

- include_tasks: "cadvisor.yml"

- include_tasks: "push.yml"

- include_tasks: "node.yml"
  when: '"node" in promfriends_contexts|default([])'

- include_tasks: "alerts.yml"

- include_tasks: "core.yml"
