---
- include_tasks: "base.yml"

- include_tasks: "snmp.yml"
  when: '"snmp" in promfriends_contexts|default([])'

- include_tasks: "blackbox.yml"
  when: '"blackbox" in promfriends_contexts|default([])'

- include_tasks: "cadvisor.yml"
  when: '"cadvisor" in promfriends_contexts|default([])'

- include_tasks: "node.yml"
  when: '"node" in promfriends_contexts|default([])'

- include_tasks: "alerts.yml"
  when: '"alerts" in promfriends_contexts|default([])'

- include_tasks: "core.yml"
  when: '"core" in promfriends_contexts|default([])'
