---
# todo switch to uv if possible
- name: "check if uv is available"
  command: "which uv"
  register: promfriends_uv_check
  changed_when: false
  ignore_errors: true

- name: "install pkg-exporter pip"
  pip:
    name: "pkg-exporter"
    state: "present"
  when: promfriends_uv_check.rc != 0

- name: "install pkg-exporter via uv"
  command: "uv tool install awscli"
  when: promfriends_uv_check.rc == 0

- name: "install pkg-exporter cron"
  ansible.builtin.cron:
    name: "promfriend node pkg-exporter"
    minute: "0,15,30,45"
    job: "PKG_EXPORTER_FILE={{promnode_text_path}}/pkg-exporter.prom \
    /usr/local/bin/pkg-exporter"
