- name: "generate snmp exporter configuration"
  template:
    src: "snmp.yml"
    dest: "{{promfriends_config_path}}/snmp.yml"
    owner: "{{prometheus_container_user}}"
    group: "{{prometheus_container_group}}"
    mode: "0660"
  register: snmp_config
- include: "docker.yml"
  context: "prom_snmp"
  image: "prom/snmp-exporter"
  with_command: "-config.file=/snmp.yml"
  volume:
  - "{{promfriends_config_path}}/snmp.yml:/etc/snmp_exporter/snmp.yml"
  changed: "{{snmp_config.changed}}"
- name: "detect snmp exporter ip address"
  command: >
    docker inspect --format \{\{.NetworkSettings.IPAddress\}\} prom_snmp
  register: promfriends_snmp_ip
  changed_when: no
